#!/usr/bin/with-contenv bash

if [ -f /etc/nginx/custom/nginx.conf ]
then
  cp /etc/nginx/custom/nginx.conf /etc/nginx/nginx.conf
fi

if [ -f /etc/nginx/custom/default.conf ]
then
  cp /etc/nginx/custom/default.conf /etc/nginx/sites-available/default
fi
