#!/usr/bin/with-contenv bash

PUID=${PUID:-9999}
PGID=${PGID:-9999}
WEBUSER_HOME=${WEBUSER_HOME:-"/var/www/html"}

if [[ $PUID != 9999 || $PGID != 9999 ]]; then
    
    # Change the User and group ID
    groupmod -o -g "$PGID" webgroup
    
    usermod -o -u "$PUID" webuser
    
    # Make sure the home directory is updated with the proper UID & GID
    chown webuser:webgroup $WEBUSER_HOME
fi

chmod -R 777 /root/
