#!/usr/bin/with-contenv bash

[ ! -f /var/log/nginx/access.log ] && touch /var/log/nginx/access.log
[ ! -f /var/log/nginx/error.log ] && touch /var/log/nginx/error.log

chown -R webuser:webgroup /var/log/nginx/
