#!/usr/bin/with-contenv bash

if [ -d /etc_custom ] && [ ! -z "$(ls -A -- "/etc_custom")" ]; then
  mkdir /root/etc_custom
  cp -r /etc_custom/* /root/etc_custom/
  chown -R root:root /root/etc_custom/
  mv -r /root/etc_custom/* /etc/
  rm /root/etc_custom/
fi
